// <auto-generated>
// This code was auto-generated by the Tools.Generator Detach project.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>

#nullable enable

using Detach.Buffers;
using Detach.Numerics;

namespace Detach.Extensions;

public static partial class BinaryWriterExtensions
{
	public static void Write(this BinaryWriter binaryWriter, Buffer4<sbyte> buffer)
	{
		for (int i = 0; i < Buffer4<sbyte>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer4<byte> buffer)
	{
		for (int i = 0; i < Buffer4<byte>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer4<short> buffer)
	{
		for (int i = 0; i < Buffer4<short>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer4<ushort> buffer)
	{
		for (int i = 0; i < Buffer4<ushort>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer4<int> buffer)
	{
		for (int i = 0; i < Buffer4<int>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer4<uint> buffer)
	{
		for (int i = 0; i < Buffer4<uint>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer4<long> buffer)
	{
		for (int i = 0; i < Buffer4<long>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer4<ulong> buffer)
	{
		for (int i = 0; i < Buffer4<ulong>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer4<Half> buffer)
	{
		for (int i = 0; i < Buffer4<Half>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer4<float> buffer)
	{
		for (int i = 0; i < Buffer4<float>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer4<double> buffer)
	{
		for (int i = 0; i < Buffer4<double>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer6<sbyte> buffer)
	{
		for (int i = 0; i < Buffer6<sbyte>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer6<byte> buffer)
	{
		for (int i = 0; i < Buffer6<byte>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer6<short> buffer)
	{
		for (int i = 0; i < Buffer6<short>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer6<ushort> buffer)
	{
		for (int i = 0; i < Buffer6<ushort>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer6<int> buffer)
	{
		for (int i = 0; i < Buffer6<int>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer6<uint> buffer)
	{
		for (int i = 0; i < Buffer6<uint>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer6<long> buffer)
	{
		for (int i = 0; i < Buffer6<long>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer6<ulong> buffer)
	{
		for (int i = 0; i < Buffer6<ulong>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer6<Half> buffer)
	{
		for (int i = 0; i < Buffer6<Half>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer6<float> buffer)
	{
		for (int i = 0; i < Buffer6<float>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer6<double> buffer)
	{
		for (int i = 0; i < Buffer6<double>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer8<sbyte> buffer)
	{
		for (int i = 0; i < Buffer8<sbyte>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer8<byte> buffer)
	{
		for (int i = 0; i < Buffer8<byte>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer8<short> buffer)
	{
		for (int i = 0; i < Buffer8<short>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer8<ushort> buffer)
	{
		for (int i = 0; i < Buffer8<ushort>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer8<int> buffer)
	{
		for (int i = 0; i < Buffer8<int>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer8<uint> buffer)
	{
		for (int i = 0; i < Buffer8<uint>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer8<long> buffer)
	{
		for (int i = 0; i < Buffer8<long>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer8<ulong> buffer)
	{
		for (int i = 0; i < Buffer8<ulong>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer8<Half> buffer)
	{
		for (int i = 0; i < Buffer8<Half>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer8<float> buffer)
	{
		for (int i = 0; i < Buffer8<float>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer8<double> buffer)
	{
		for (int i = 0; i < Buffer8<double>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer12<sbyte> buffer)
	{
		for (int i = 0; i < Buffer12<sbyte>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer12<byte> buffer)
	{
		for (int i = 0; i < Buffer12<byte>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer12<short> buffer)
	{
		for (int i = 0; i < Buffer12<short>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer12<ushort> buffer)
	{
		for (int i = 0; i < Buffer12<ushort>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer12<int> buffer)
	{
		for (int i = 0; i < Buffer12<int>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer12<uint> buffer)
	{
		for (int i = 0; i < Buffer12<uint>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer12<long> buffer)
	{
		for (int i = 0; i < Buffer12<long>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer12<ulong> buffer)
	{
		for (int i = 0; i < Buffer12<ulong>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer12<Half> buffer)
	{
		for (int i = 0; i < Buffer12<Half>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer12<float> buffer)
	{
		for (int i = 0; i < Buffer12<float>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer12<double> buffer)
	{
		for (int i = 0; i < Buffer12<double>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer16<sbyte> buffer)
	{
		for (int i = 0; i < Buffer16<sbyte>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer16<byte> buffer)
	{
		for (int i = 0; i < Buffer16<byte>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer16<short> buffer)
	{
		for (int i = 0; i < Buffer16<short>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer16<ushort> buffer)
	{
		for (int i = 0; i < Buffer16<ushort>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer16<int> buffer)
	{
		for (int i = 0; i < Buffer16<int>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer16<uint> buffer)
	{
		for (int i = 0; i < Buffer16<uint>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer16<long> buffer)
	{
		for (int i = 0; i < Buffer16<long>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer16<ulong> buffer)
	{
		for (int i = 0; i < Buffer16<ulong>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer16<Half> buffer)
	{
		for (int i = 0; i < Buffer16<Half>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer16<float> buffer)
	{
		for (int i = 0; i < Buffer16<float>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer16<double> buffer)
	{
		for (int i = 0; i < Buffer16<double>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer24<sbyte> buffer)
	{
		for (int i = 0; i < Buffer24<sbyte>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer24<byte> buffer)
	{
		for (int i = 0; i < Buffer24<byte>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer24<short> buffer)
	{
		for (int i = 0; i < Buffer24<short>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer24<ushort> buffer)
	{
		for (int i = 0; i < Buffer24<ushort>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer24<int> buffer)
	{
		for (int i = 0; i < Buffer24<int>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer24<uint> buffer)
	{
		for (int i = 0; i < Buffer24<uint>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer24<long> buffer)
	{
		for (int i = 0; i < Buffer24<long>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer24<ulong> buffer)
	{
		for (int i = 0; i < Buffer24<ulong>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer24<Half> buffer)
	{
		for (int i = 0; i < Buffer24<Half>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer24<float> buffer)
	{
		for (int i = 0; i < Buffer24<float>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer24<double> buffer)
	{
		for (int i = 0; i < Buffer24<double>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer32<sbyte> buffer)
	{
		for (int i = 0; i < Buffer32<sbyte>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer32<byte> buffer)
	{
		for (int i = 0; i < Buffer32<byte>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer32<short> buffer)
	{
		for (int i = 0; i < Buffer32<short>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer32<ushort> buffer)
	{
		for (int i = 0; i < Buffer32<ushort>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer32<int> buffer)
	{
		for (int i = 0; i < Buffer32<int>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer32<uint> buffer)
	{
		for (int i = 0; i < Buffer32<uint>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer32<long> buffer)
	{
		for (int i = 0; i < Buffer32<long>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer32<ulong> buffer)
	{
		for (int i = 0; i < Buffer32<ulong>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer32<Half> buffer)
	{
		for (int i = 0; i < Buffer32<Half>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer32<float> buffer)
	{
		for (int i = 0; i < Buffer32<float>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

	public static void Write(this BinaryWriter binaryWriter, Buffer32<double> buffer)
	{
		for (int i = 0; i < Buffer32<double>.Size; i++)
			binaryWriter.Write(buffer[i]);
	}

}
