namespace Detach.CodeGeneration;

internal static class GeneratorConstants
{
	public const char NewLine = '\n';

	public const char Indentation = '\t';

	public const string Header =
		"""
		// <auto-generated>
		// This code was auto-generated.
		// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
		// </auto-generated>

		#nullable enable
		""";
}
